## UNIFICACIÓN DE DATOS DE WEB SCRAPING

In [2]:
import pandas as pd
import glob
import os

# 1. Le decimos a Python dónde están los archivos
#ruta = "*.csv"
ruta = "/content/*.csv"

# 2. Buscamos todos los archivos CSV de la carpeta
archivos_csv = glob.glob(ruta)
print(f"He encontrado {len(archivos_csv)} archivos CSV para unir.")

# 3. Creamos una lista vacía y vamos leyendo y guardando cada CSV
lista_dataframes = []

for archivo in archivos_csv:
    # Leemos cada archivo (suponemos que están separados por comas)
    df_temporal = pd.read_csv(archivo)
    lista_dataframes.append(df_temporal)

# 4. Unimos todos los recortes en una sola tabla gigante
df_total = pd.concat(lista_dataframes, ignore_index=True)
print(f"Total de reseñas combinadas en bruto: {len(df_total)}")

# 5. Eliminar duplicados (mismo hotel o reseña 2 veces)
df_total = df_total.drop_duplicates()

# 6. Ética y Privacidad (Borramos el nombre del usuario si existe)
# Cambia 'nombre_usuario' por el nombre exacto que le pusisteis a esa columna en Web Scraper
nombre_columna_usuario = 'nombre_usuario'
if nombre_columna_usuario in df_total.columns:
    df_total = df_total.drop(columns=[nombre_columna_usuario])
    print("✓ Nombres de usuario borrados por privacidad (Cumplimiento RGPD).")


print(f"Total de reseñas finales listas para NLP: {len(df_total)}")

# 7. Exportamos el súper archivo final
df_total.to_csv("df_hoteles_vlc_completo.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_completo.csv' creado con éxito!")

He encontrado 8 archivos CSV para unir.
Total de reseñas combinadas en bruto: 58720
✓ Nombres de usuario borrados por privacidad (Cumplimiento RGPD).
Total de reseñas finales listas para NLP: 58720
¡Archivo 'df_hoteles_vlc_completo.csv' creado con éxito!

In [3]:
display(df_total.head())

,web_scraper_order,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,...,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,1776260909-1,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,NaN,1 noche ·,En pareja,Un finde perfecto,El desayuno super completo y la ubicacion inme...,Lo unico que no me gusto es que solo me quede ...,...,Fecha del comentario: 13 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
1,1776260909-2,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Doble Estándar con vistas a la plaz...,1 noche ·,En pareja,Muy bien,"Todo en general, muy bien",NaN,...,Fecha del comentario: 9 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
2,1776260909-3,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,Argentina,Habitación Estándar,2 noches ·,En familia,Excepcional,La habitación y el baño,NaN,...,Fecha del comentario: 8 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
3,1776260909-4,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Estándar,2 noches ·,En familia,Excepcional,"Ubicación muy buena, habitación excelente",Los de recepción muy serios,...,Fecha del comentario: 6 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
4,1776260909-5,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Cuádruple Estándar,1 noche ·,En familia,Increíble,Está en una buena ubicación y hotel muy limpio...,NaN,...,Fecha del comentario: 4 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico

In [4]:
#hacemos una copia del dataframe original para no perderlo
df_original= df_total.copy()

## Preprocesado y limpieza del dataset

In [5]:
#eliminar columna de web order
df_total = df_total.drop(columns=['web_scraper_order'])
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,NaN,1 noche ·,En pareja,Un finde perfecto,El desayuno super completo y la ubicacion inme...,Lo unico que no me gusto es que solo me quede ...,10,Fecha del comentario: 13 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
1,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Doble Estándar con vistas a la plaz...,1 noche ·,En pareja,Muy bien,"Todo en general, muy bien",NaN,10,Fecha del comentario: 9 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
2,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,Argentina,Habitación Estándar,2 noches ·,En familia,Excepcional,La habitación y el baño,NaN,10,Fecha del comentario: 8 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
3,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Estándar,2 noches ·,En familia,Excepcional,"Ubicación muy buena, habitación excelente",Los de recepción muy serios,10,Fecha del comentario: 6 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
4,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Cuádruple Estándar,1 noche ·,En familia,Increíble,Está en una buena ubicación y hotel muy limpio...,NaN,10,Fecha del comentario: 4 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico

In [6]:
#de la columna noches extraemos el número de noches y actualizamos la columna, pasamos el digito a entero
df_total['noches'] = df_total['noches'].str.extract('(\d+)').astype(int)
display(df_total.head())

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_13130/3682110897.py:2: SyntaxWarning: invalid escape sequence '\d'
  df_total['noches'] = df_total['noches'].str.extract('(\d+)').astype(int)

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,NaN,1,En pareja,Un finde perfecto,El desayuno super completo y la ubicacion inme...,Lo unico que no me gusto es que solo me quede ...,10,Fecha del comentario: 13 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
1,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Doble Estándar con vistas a la plaz...,1,En pareja,Muy bien,"Todo en general, muy bien",NaN,10,Fecha del comentario: 9 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
2,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,Argentina,Habitación Estándar,2,En familia,Excepcional,La habitación y el baño,NaN,10,Fecha del comentario: 8 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
3,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Estándar,2,En familia,Excepcional,"Ubicación muy buena, habitación excelente",Los de recepción muy serios,10,Fecha del comentario: 6 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
4,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Cuádruple Estándar,1,En familia,Increíble,Está en una buena ubicación y hotel muy limpio...,NaN,10,Fecha del comentario: 4 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico

In [7]:
#si la columna de negativo o positivo SOLO tiene un punto, lo convertimos a NA
df_total['negativo'] = df_total['negativo'].replace('.', pd.NA)
df_total['positivo'] = df_total['positivo'].replace('.', pd.NA)
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,NaN,1,En pareja,Un finde perfecto,El desayuno super completo y la ubicacion inme...,Lo unico que no me gusto es que solo me quede ...,10,Fecha del comentario: 13 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
1,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Doble Estándar con vistas a la plaz...,1,En pareja,Muy bien,"Todo en general, muy bien",NaN,10,Fecha del comentario: 9 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
2,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,Argentina,Habitación Estándar,2,En familia,Excepcional,La habitación y el baño,NaN,10,Fecha del comentario: 8 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
3,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Estándar,2,En familia,Excepcional,"Ubicación muy buena, habitación excelente",Los de recepción muy serios,10,Fecha del comentario: 6 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico
4,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Cuádruple Estándar,1,En familia,Increíble,Está en una buena ubicación y hotel muy limpio...,NaN,10,Fecha del comentario: 4 de abril de 2026,"9,5","9,4","8,9","9,1","9,0","9,4","9,9","9,2",Fantástico

In [8]:
#todas las columnas de nota cambiamos las comas por puntos y las convertimos a numéricas
#coger las columnas que empiezan por 'nota'
columnas_notas = [col for col in df_total.columns if col.startswith('nota')]
for columna in columnas_notas:
    df_total[columna] = df_total[columna].str.replace(',', '.')
    df_total[columna] = pd.to_numeric(df_total[columna], errors='coerce')
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,NaN,1,En pareja,Un finde perfecto,El desayuno super completo y la ubicacion inme...,Lo unico que no me gusto es que solo me quede ...,10.0,Fecha del comentario: 13 de abril de 2026,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
1,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Doble Estándar con vistas a la plaz...,1,En pareja,Muy bien,"Todo en general, muy bien",NaN,10.0,Fecha del comentario: 9 de abril de 2026,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
2,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,Argentina,Habitación Estándar,2,En familia,Excepcional,La habitación y el baño,NaN,10.0,Fecha del comentario: 8 de abril de 2026,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
3,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Estándar,2,En familia,Excepcional,"Ubicación muy buena, habitación excelente",Los de recepción muy serios,10.0,Fecha del comentario: 6 de abril de 2026,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
4,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Cuádruple Estándar,1,En familia,Increíble,Está en una buena ubicación y hotel muy limpio...,NaN,10.0,Fecha del comentario: 4 de abril de 2026,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico

In [9]:
#cogemos la columna de fecha, queremos quedarnos SOLO con la fecha y despues convertirla a formato datetime
#ahora las celdas son estilo: "Fecha del comentario, 14 de marzo de 2023"
df_total['fecha'] = df_total['fecha'].str.extract('(\d{1,2} de \w+ de \d{4})')
df_total['fecha'] = pd.to_datetime(df_total['fecha'], format='%d de %B de %Y', errors='coerce')
#quitar la hora de la fecha, solo queremos la fecha
df_total['fecha'] = df_total['fecha'].dt.date
display(df_total.head())

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_13130/2605996928.py:3: SyntaxWarning: invalid escape sequence '\d'
  df_total['fecha'] = df_total['fecha'].str.extract('(\d{1,2} de \w+ de \d{4})')

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,NaN,1,En pareja,Un finde perfecto,El desayuno super completo y la ubicacion inme...,Lo unico que no me gusto es que solo me quede ...,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
1,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Doble Estándar con vistas a la plaz...,1,En pareja,Muy bien,"Todo en general, muy bien",NaN,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
2,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,Argentina,Habitación Estándar,2,En familia,Excepcional,La habitación y el baño,NaN,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
3,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Estándar,2,En familia,Excepcional,"Ubicación muy buena, habitación excelente",Los de recepción muy serios,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
4,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Cuádruple Estándar,1,En familia,Increíble,Está en una buena ubicación y hotel muy limpio...,NaN,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico

In [10]:
#quitar el "En" de la columna de personas, ahora tiene formato "En familia", "En pareja", "Solo", etc. Queremos quedarnos solo con el tipo de persona, sin el "En"
df_total['personas'] = df_total['personas'].str.replace('En ', '')
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,NaN,1,pareja,Un finde perfecto,El desayuno super completo y la ubicacion inme...,Lo unico que no me gusto es que solo me quede ...,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
1,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Doble Estándar con vistas a la plaz...,1,pareja,Muy bien,"Todo en general, muy bien",NaN,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
2,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,Argentina,Habitación Estándar,2,familia,Excepcional,La habitación y el baño,NaN,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
3,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Estándar,2,familia,Excepcional,"Ubicación muy buena, habitación excelente",Los de recepción muy serios,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico
4,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,España,Habitación Cuádruple Estándar,1,familia,Increíble,Está en una buena ubicación y hotel muy limpio...,NaN,10.0,NaT,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2,Fantástico

Vamos a crear un csv aparte que contenga la información del hotel y otro csv con la información de los comentarios, para luego unirlos por el id del hotel.
Para el csv de los hoteles, vamos a quedarnos con las columnas: web_scraper_start_url, nombre_del_hotel, y las que empiecen por "nota_". Para el csv de los comentarios, nos quedaremos con el resto de columnas, incluyendo el id del hotel que identificará cada hotel en el primer csv.

In [11]:
#Vamos a crear un csv aparte que contenga la información del hotel y otro csv con la información de los comentarios, para luego unirlos por el id del hotel.
#Para el csv de los hoteles, vamos a quedarnos con las columnas: web_scraper_start_url, nombre_del_hotel, y las que empiecen por "nota_". Para el csv de los comentarios, nos quedaremos con el resto de columnas, incluyendo el id del hotel que identificará cada hotel en el primer csv.
#el id del hotel viene del nombre del hotel, que es único para cada hotel, así que lo usaremos como id para unir los csv después.

#creamos el csv de hoteles
columnas_hoteles = ['web_scraper_start_url', 'nombre_del_hotel'] + [col for col in df_total.columns if col.startswith('nota_')]
df_hoteles = df_total[columnas_hoteles].drop_duplicates()
df_hoteles.to_csv("df_hoteles_vlc_info.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_info.csv' creado con éxito!")

#creamos el csv de comentarios
columnas_comentarios = [col for col in df_total.columns if col not in columnas_hoteles]
df_comentarios = df_total[columnas_comentarios]
df_comentarios.to_csv("df_hoteles_vlc_comentarios.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_comentarios.csv' creado con éxito!")

¡Archivo 'df_hoteles_vlc_info.csv' creado con éxito!
¡Archivo 'df_hoteles_vlc_comentarios.csv' creado con éxito!

In [12]:
display(df_hoteles)

,web_scraper_start_url,nombre_del_hotel,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas
0,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2
9877,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6
13231,https://www.booking.com/hotel/es/the-river-hos...,The River Hostel,8.9,8.3,8.2,8.3,8.6,8.4,9.1,8.2
19765,https://www.booking.com/hotel/es/renasa.es.htm...,Sweet Hotel Renasa,8.8,8.4,8.0,8.0,7.9,8.5,8.3,8.1
23756,https://www.booking.com/hotel/es/puertavalenci...,Silken Puerta Valencia,9.0,8.9,8.2,8.6,8.3,9.0,8.4,8.6
28168,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8
30276,https://www.booking.com/hotel/es/only-you-vale...,Only YOU Hotel Valencia,9.7,9.6,9.1,9.4,8.9,9.6,9.8,9.4
35613,https://www.booking.com/hotel/es/casual-valenc...,Casual del Cine Valencia by Casual Hoteles,9.4,8.7,8.8,8.3,8.4,8.8,9.7,8.5
39575,https://www.booking.com/hotel/es/nh-valencia-l...,NH Valencia Las Ciencias,8.7,8.2,7.8,7.8,7.6,8.4,8.9,7.9
44283,https://www.booking.com/hotel/es/confortel-aqu...,Ilunion Aqua 3,8.6,8.2,8.5,7.8,7.6,8.3,9.0,7.9
48403,https://www.booking.com/hotel/es/las-arenas-ca...,Hotel Las Arenas Balneario Resort,8.9,8.9,8.3,8.6,8.5,8.9,9.2,8.6
51403,https://www.booking.com/hotel/es/casual-valenc...,Casual Vintage Valencia,9.3,8.6,8.6,8.2,8.4,8.7,9.8,8.4

## Limpieza (minúsculas, enlaces y caracteres, emoticonos)

In [13]:
!pip install demoji -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.4/43.4 kB 547.1 kB/s eta 0:00:00

In [14]:
import re
import demoji

# Traducir emojis
# Los traduce al inglés (tendremos que mirar si los traducimos al español todos o a qué idioma)
def handle_emoji(string):
    if not isinstance(string, str):
        return string
    emojis = demoji.findall(string)
    for emoji in emojis:
        string = string.replace(emoji, " [" + emojis[emoji].split(":")[0].strip() + "] ")
    return string

string_cols = df_comentarios.select_dtypes(include=['object', 'string']).columns
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.apply(handle_emoji))

# Todo a minúscula
string_cols = df_comentarios.select_dtypes(include=['object', 'string']).columns
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.lower())

# Eliminar enlaces y limpiar espacios
string_cols = df_comentarios.select_dtypes(include=['object', 'string']).columns
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.replace(r'https?://\S+|www\.\S+', '', regex=True).str.strip())

# Eliminar caracteres especiales
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.replace(r'[^a-záéíóúüñàèìòùâêîôûäëïöüa-z0-9\s\[\].,!?;:\-]', ' ', regex=True))

/tmp/ipykernel_13130/2932701220.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.apply(handle_emoji))
/tmp/ipykernel_13130/2932701220.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.lower())
/tmp/ipykernel_13130/2932701220.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.replace(r'https?://\S+|www\.\S+', '', regex=True).str.strip())
/tmp/ipykernel_13130/2932701220.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.replace(r'[^a-záéíóúüñàèìòùâêîôûäëïöüa-z0-9\s\[\].,!?;:\-]', ' ', regex=True))

In [15]:
df_comentarios.to_csv("df_comentarios_limpio.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_comentarios_limpio.csv' creado con éxito!")

¡Archivo 'df_comentarios_limpio.csv' creado con éxito!

In [16]:
display(df_comentarios)

,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,comentario_media_hotel
0,españa,NaN,1,pareja,un finde perfecto,el desayuno super completo y la ubicacion inme...,lo unico que no me gusto es que solo me quede ...,10.0,NaT,fantástico
1,españa,habitación doble estándar con vistas a la plaz...,1,pareja,muy bien,"todo en general, muy bien",NaN,10.0,NaT,fantástico
2,argentina,habitación estándar,2,familia,excepcional,la habitación y el baño,NaN,10.0,NaT,fantástico
3,españa,habitación estándar,2,familia,excepcional,"ubicación muy buena, habitación excelente",los de recepción muy serios,10.0,NaT,fantástico
4,españa,habitación cuádruple estándar,1,familia,increíble,está en una buena ubicación y hotel muy limpio...,NaN,10.0,NaT,fantástico
...,...,...,...,...,...,...,...,...,...,...
58715,países bajos,NaN,3,pareja,muy bien,NaN,NaN,8.0,NaT,muy bien
58716,italia,habitación interior individual pequeña,3,persona que viaja sola,fantástico,NaN,NaN,9.0,NaT,muy bien
58717,países bajos,habitación doble - 2 camas,2,pareja,muy bien,NaN,NaN,8.0,NaT,muy bien
58718,italia,habitación doble,2,pareja,excepcional,NaN,NaN,10.0,NaT,muy bien
58719,francia,NaN,1,pareja,agradable,NaN,NaN,6.0,NaT,muy bien

## FUNCIONES PREVIAS A LA TRADUCCIÓN AL ESPAÑOL:
(Uso de GPU)

In [17]:
!pip install deep-translator -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 1.3 MB/s eta 0:00:00

In [19]:
!pip install langdetect -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for langdetect (setup.py) ... done

In [20]:
# Librerías
from langdetect import detect, LangDetectException
from deep_translator import GoogleTranslator
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
import os
import time # Importamos el módulo time

In [21]:
def detectar_idioma(texto):
    try:
        if pd.isna(texto) or str(texto).strip() == '': # si es un NA o sólo espacios vacíos no se traduce
            return 'es'
        return detect(str(texto)) # devuelve un string con el idioma en el que está
    except LangDetectException:
        return 'desconocido' #si no entiende el idioma devuelve desconocido

In [22]:
def traducir_lote(textos):
    try:
        return GoogleTranslator(source='auto', target='es').translate_batch(textos) #le decimos coge el idioma que sea y me lo pasas al español y translate batch es para traducir por lotes
    except Exception as e:
        print(f"Error en lote: {e}")
        return textos  # si falla, devuelve los originales

# GESTIÓN DE NAN:

In [23]:
def gestionar_nulos(df, columnas):
    for col in columnas:
        df[col] = df[col].fillna('')
    df = df[~df[columnas].apply(lambda row: all(v == '' for v in row), axis=1)] # comprobación de si en una fila están todas las columnas vacías y nos quedamos con las que no son nan
    return df

# TRADUCCIÓN COMPLETA:

In [24]:
def traduccion(columna, tamaño_lote=50, max_workers=10, checkpoint_path='checkpoint.csv', delay_between_batches=1): # detecta el idioma y si no es español lo traduce
    print("  Detectando idiomas...")
    idiomas = columna.apply(detectar_idioma)

    mask_traducir = idiomas != 'es'
    indices_traducir = columna[mask_traducir].index
    textos_traducir = columna[mask_traducir].tolist()

    print(f"  Total: {len(columna)} | En español: {(~mask_traducir).sum()} | A traducir: {mask_traducir.sum()}")

    resultado = columna.copy()

    # Cargar checkpoint si existe (por si se cayó antes)
    if os.path.exists(checkpoint_path):
        print("  Cargando checkpoint previo...")
        checkpoint = pd.read_csv(checkpoint_path, index_col=0).squeeze()
        ya_hechos = checkpoint.index
        indices_traducir = indices_traducir.difference(ya_hechos)
        textos_traducir = columna[indices_traducir].tolist()
        resultado.update(checkpoint)
        print(f"  Ya traducidos: {len(ya_hechos)} | Quedan: {len(textos_traducir)}")

    # Crear lotes
    lotes = [
        (textos_traducir[i:i+tamaño_lote], indices_traducir[i:i+tamaño_lote])
        for i in range(0, len(textos_traducir), tamaño_lote)
    ]
    total_lotes = len(lotes)
    completados = 0

    # Traducir en paralelo
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futuros = {
            executor.submit(traducir_lote, lote): indices
            for lote, indices in lotes
        }

        for futuro in as_completed(futuros):
            indices_lote = futuros[futuro]
            try:
                traducidos = futuro.result()
                for idx, texto in zip(indices_lote, traducidos):
                    resultado[idx] = texto
            except Exception as e:
                print(f"  Error en lote: {e}")

            completados += 1

            # Guardar checkpoint cada 50 lotes
            if completados % 50 == 0:
                resultado[mask_traducir].to_csv(checkpoint_path)
                print(f"  {completados}/{total_lotes} lotes completados ({completados/total_lotes*100:.1f}%) -- Checkpoint guardado")

            # Añadir un retardo entre lotes para evitar bloqueos por rate limit
            time.sleep(delay_between_batches)

    # Guardar checkpoint final
    resultado[mask_traducir].to_csv(checkpoint_path)
    print("Traducción completada!")
    return resultado

# EJECUCIÓN:

In [25]:
df_comentarios_limpio = pd.read_csv('/content/df_comentarios_limpio.csv')

df_comentarios_limpio = gestionar_nulos(df_comentarios_limpio, df_comentarios_limpio.columns.tolist())
print(df_comentarios_limpio.shape)
df_comentarios_limpio.head()

(58720, 10)

,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,comentario_media_hotel
0,españa,,1,pareja,un finde perfecto,el desayuno super completo y la ubicacion inme...,lo unico que no me gusto es que solo me quede ...,10.0,,fantástico
1,españa,habitación doble estándar con vistas a la plaz...,1,pareja,muy bien,"todo en general, muy bien",,10.0,,fantástico
2,argentina,habitación estándar,2,familia,excepcional,la habitación y el baño,,10.0,,fantástico
3,españa,habitación estándar,2,familia,excepcional,"ubicación muy buena, habitación excelente",los de recepción muy serios,10.0,,fantástico
4,españa,habitación cuádruple estándar,1,familia,increíble,está en una buena ubicación y hotel muy limpio...,,10.0,,fantástico

In [26]:
df_comentarios_limpio['comentario_general'] = traduccion(
    df_comentarios_limpio['comentario_general'],
    tamaño_lote=16,
    checkpoint_path='ckpt_comentario_general.csv',
    delay_between_batches=5 # Aumentamos el retardo para evitar el límite de peticiones
)

  Detectando idiomas...
  Total: 58720 | En español: 25850 | A traducir: 32870
  50/2055 lotes completados (2.4%) -- Checkpoint guardado
  100/2055 lotes completados (4.9%) -- Checkpoint guardado
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function
Error en lote: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function

KeyboardInterrupt:

In [ ]:
df_comentarios_limpio['positivo'] = traduccion(
    df_comentarios_limpio['positivo'],
    tamaño_lote=16,
    checkpoint_path='ckpt_positivo.csv',
    delay_between_batches=5 # Aumentamos el retardo
)

In [ ]:
df_comentarios_limpio['negativo'] = traduccion(
    df_comentarios_limpio['negativo'],
    tamaño_lote=16,
    checkpoint_path='ckpt_negativo.csv',
    delay_between_batches=5 # Aumentamos el retardo
)

In [ ]:
df_comentarios_limpio.to_csv('comentarios_traducidos.csv', index=False)
print('Archivo guardado: comentarios_traducidos.csv')
df_comentarios_limpio.head()