## UNIFICACIÓN DE DATOS DE WEB SCRAPING

In [1]:
import pandas as pd
import glob
import os

# 1. Le decimos a Python dónde están los archivos 
ruta = "*.csv" 

# 2. Buscamos todos los archivos CSV de la carpeta
archivos_csv = glob.glob(ruta)
print(f"He encontrado {len(archivos_csv)} archivos CSV para unir.")

# 3. Creamos una lista vacía y vamos leyendo y guardando cada CSV
lista_dataframes = []

for archivo in archivos_csv:
    # Leemos cada archivo (suponemos que están separados por comas)
    df_temporal = pd.read_csv(archivo)
    lista_dataframes.append(df_temporal)

# 4. Unimos todos los recortes en una sola tabla gigante
df_total = pd.concat(lista_dataframes, ignore_index=True)
print(f"Total de reseñas combinadas en bruto: {len(df_total)}")

# 5. Eliminar duplicados (mismo hotel o reseña 2 veces)
df_total = df_total.drop_duplicates()

# 6. Ética y Privacidad (Borramos el nombre del usuario si existe)
# Cambia 'nombre_usuario' por el nombre exacto que le pusisteis a esa columna en Web Scraper
nombre_columna_usuario = 'nombre_usuario' 
if nombre_columna_usuario in df_total.columns:
    df_total = df_total.drop(columns=[nombre_columna_usuario])
    print("✓ Nombres de usuario borrados por privacidad (Cumplimiento RGPD).")


print(f"Total de reseñas finales listas para NLP: {len(df_total)}")

# 7. Exportamos el súper archivo final
df_total.to_csv("df_hoteles_vlc_completo.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_completo.csv' creado con éxito!")

He encontrado 8 archivos CSV para unir.
Total de reseñas combinadas en bruto: 58720
✓ Nombres de usuario borrados por privacidad (Cumplimiento RGPD).
Total de reseñas finales listas para NLP: 58720
¡Archivo 'df_hoteles_vlc_completo.csv' creado con éxito!

In [2]:
display(df_total.head())

,web_scraper_order,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,...,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,1776375264-1,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Meliá con 1 cama extragrande,1 noche ·,En pareja,Excelente,"Todo la habitación súper amplia, la cama extra...",NaN,...,Fecha del comentario: 15 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
1,1776375264-2,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Supreme,1 noche ·,Persona que viaja sola,Mi referente para alojarme en Valencia,Ya lo conocía de anteriores estancias. Me enca...,NaN,...,Fecha del comentario: 11 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
2,1776375264-3,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Chile,Habitación Meliá con 1 cama extragrande,3 noches ·,En pareja,Hotel funcional en lugar alejado,El lobby y cafeteria,Ascensores lentos,...,Fecha del comentario: 10 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
3,1776375264-4,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Alojamiento The Level Supreme,3 noches ·,En familia,Solo perfecto!,Habitacion a la planta 24 (high level) - a est...,NaN,...,Fecha del comentario: 7 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
4,1776375264-5,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Perú,Habitación Meliá,2 noches ·,En familia,Fantástico,"Habitación cómoda, la ubicación muy buena y el...",NaN,...,Fecha del comentario: 1 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso

In [3]:
#hacemos una copia del dataframe original para no perderlo
df_original= df_total.copy()

## Preprocesado y limpieza del dataset

In [4]:
#eliminar columna de web order
df_total = df_total.drop(columns=['web_scraper_order'])
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Meliá con 1 cama extragrande,1 noche ·,En pareja,Excelente,"Todo la habitación súper amplia, la cama extra...",NaN,10,Fecha del comentario: 15 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
1,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Supreme,1 noche ·,Persona que viaja sola,Mi referente para alojarme en Valencia,Ya lo conocía de anteriores estancias. Me enca...,NaN,"9,0",Fecha del comentario: 11 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
2,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Chile,Habitación Meliá con 1 cama extragrande,3 noches ·,En pareja,Hotel funcional en lugar alejado,El lobby y cafeteria,Ascensores lentos,"8,0",Fecha del comentario: 10 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
3,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Alojamiento The Level Supreme,3 noches ·,En familia,Solo perfecto!,Habitacion a la planta 24 (high level) - a est...,NaN,10,Fecha del comentario: 7 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
4,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Perú,Habitación Meliá,2 noches ·,En familia,Fantástico,"Habitación cómoda, la ubicación muy buena y el...",NaN,"9,0",Fecha del comentario: 1 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso

In [5]:
#de la columna noches extraemos el número de noches y actualizamos la columna, pasamos el digito a entero
df_total['noches'] = df_total['noches'].str.extract('(\d+)').astype(int)
display(df_total.head())

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/var/folders/bf/hdjf592s2t51ng0dsl8jlg8h0000gn/T/ipykernel_27494/3682110897.py:2: SyntaxWarning: invalid escape sequence '\d'
  df_total['noches'] = df_total['noches'].str.extract('(\d+)').astype(int)

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Meliá con 1 cama extragrande,1,En pareja,Excelente,"Todo la habitación súper amplia, la cama extra...",NaN,10,Fecha del comentario: 15 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
1,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Supreme,1,Persona que viaja sola,Mi referente para alojarme en Valencia,Ya lo conocía de anteriores estancias. Me enca...,NaN,"9,0",Fecha del comentario: 11 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
2,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Chile,Habitación Meliá con 1 cama extragrande,3,En pareja,Hotel funcional en lugar alejado,El lobby y cafeteria,Ascensores lentos,"8,0",Fecha del comentario: 10 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
3,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Alojamiento The Level Supreme,3,En familia,Solo perfecto!,Habitacion a la planta 24 (high level) - a est...,NaN,10,Fecha del comentario: 7 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
4,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Perú,Habitación Meliá,2,En familia,Fantástico,"Habitación cómoda, la ubicación muy buena y el...",NaN,"9,0",Fecha del comentario: 1 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso

In [6]:
#si la columna de negativo o positivo SOLO tiene un punto, lo convertimos a NA
df_total['negativo'] = df_total['negativo'].replace('.', pd.NA)
df_total['positivo'] = df_total['positivo'].replace('.', pd.NA)
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Meliá con 1 cama extragrande,1,En pareja,Excelente,"Todo la habitación súper amplia, la cama extra...",NaN,10,Fecha del comentario: 15 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
1,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Supreme,1,Persona que viaja sola,Mi referente para alojarme en Valencia,Ya lo conocía de anteriores estancias. Me enca...,NaN,"9,0",Fecha del comentario: 11 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
2,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Chile,Habitación Meliá con 1 cama extragrande,3,En pareja,Hotel funcional en lugar alejado,El lobby y cafeteria,Ascensores lentos,"8,0",Fecha del comentario: 10 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
3,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Alojamiento The Level Supreme,3,En familia,Solo perfecto!,Habitacion a la planta 24 (high level) - a est...,NaN,10,Fecha del comentario: 7 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso
4,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Perú,Habitación Meliá,2,En familia,Fantástico,"Habitación cómoda, la ubicación muy buena y el...",NaN,"9,0",Fecha del comentario: 1 de abril de 2026,"9,0","9,1",NaN,"8,8","8,3","9,0","8,3","8,6",Fabuloso

In [7]:
#todas las columnas de nota cambiamos las comas por puntos y las convertimos a numéricas
#coger las columnas que empiezan por 'nota'
columnas_notas = [col for col in df_total.columns if col.startswith('nota')]
for columna in columnas_notas:
    df_total[columna] = df_total[columna].str.replace(',', '.')
    df_total[columna] = pd.to_numeric(df_total[columna], errors='coerce')
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Meliá con 1 cama extragrande,1,En pareja,Excelente,"Todo la habitación súper amplia, la cama extra...",NaN,10.0,Fecha del comentario: 15 de abril de 2026,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
1,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Supreme,1,Persona que viaja sola,Mi referente para alojarme en Valencia,Ya lo conocía de anteriores estancias. Me enca...,NaN,9.0,Fecha del comentario: 11 de abril de 2026,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
2,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Chile,Habitación Meliá con 1 cama extragrande,3,En pareja,Hotel funcional en lugar alejado,El lobby y cafeteria,Ascensores lentos,8.0,Fecha del comentario: 10 de abril de 2026,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
3,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Alojamiento The Level Supreme,3,En familia,Solo perfecto!,Habitacion a la planta 24 (high level) - a est...,NaN,10.0,Fecha del comentario: 7 de abril de 2026,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
4,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Perú,Habitación Meliá,2,En familia,Fantástico,"Habitación cómoda, la ubicación muy buena y el...",NaN,9.0,Fecha del comentario: 1 de abril de 2026,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso

In [8]:
#cogemos la columna de fecha, queremos quedarnos SOLO con la fecha y despues convertirla a formato datetime
#ahora las celdas son estilo: "Fecha del comentario, 14 de marzo de 2023"
df_total['fecha'] = df_total['fecha'].str.extract('(\d{1,2} de \w+ de \d{4})')
df_total['fecha'] = pd.to_datetime(df_total['fecha'], format='%d de %B de %Y', errors='coerce')
#quitar la hora de la fecha, solo queremos la fecha
df_total['fecha'] = df_total['fecha'].dt.date
display(df_total.head())

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
/var/folders/bf/hdjf592s2t51ng0dsl8jlg8h0000gn/T/ipykernel_27494/2605996928.py:3: SyntaxWarning: invalid escape sequence '\d'
  df_total['fecha'] = df_total['fecha'].str.extract('(\d{1,2} de \w+ de \d{4})')

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Meliá con 1 cama extragrande,1,En pareja,Excelente,"Todo la habitación súper amplia, la cama extra...",NaN,10.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
1,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Supreme,1,Persona que viaja sola,Mi referente para alojarme en Valencia,Ya lo conocía de anteriores estancias. Me enca...,NaN,9.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
2,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Chile,Habitación Meliá con 1 cama extragrande,3,En pareja,Hotel funcional en lugar alejado,El lobby y cafeteria,Ascensores lentos,8.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
3,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Alojamiento The Level Supreme,3,En familia,Solo perfecto!,Habitacion a la planta 24 (high level) - a est...,NaN,10.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
4,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Perú,Habitación Meliá,2,En familia,Fantástico,"Habitación cómoda, la ubicación muy buena y el...",NaN,9.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso

In [9]:
#quitar el "En" de la columna de personas, ahora tiene formato "En familia", "En pareja", "Solo", etc. Queremos quedarnos solo con el tipo de persona, sin el "En"
df_total['personas'] = df_total['personas'].str.replace('En ', '')
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Meliá con 1 cama extragrande,1,pareja,Excelente,"Todo la habitación súper amplia, la cama extra...",NaN,10.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
1,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Habitación Supreme,1,Persona que viaja sola,Mi referente para alojarme en Valencia,Ya lo conocía de anteriores estancias. Me enca...,NaN,9.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
2,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Chile,Habitación Meliá con 1 cama extragrande,3,pareja,Hotel funcional en lugar alejado,El lobby y cafeteria,Ascensores lentos,8.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
3,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,España,Alojamiento The Level Supreme,3,familia,Solo perfecto!,Habitacion a la planta 24 (high level) - a est...,NaN,10.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso
4,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,Perú,Habitación Meliá,2,familia,Fantástico,"Habitación cómoda, la ubicación muy buena y el...",NaN,9.0,NaT,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6,Fabuloso

Vamos a crear un csv aparte que contenga la información del hotel y otro csv con la información de los comentarios, para luego unirlos por el id del hotel.
Para el csv de los hoteles, vamos a quedarnos con las columnas: web_scraper_start_url, nombre_del_hotel, y las que empiecen por "nota_". Para el csv de los comentarios, nos quedaremos con el resto de columnas, incluyendo el id del hotel que identificará cada hotel en el primer csv.

In [10]:
#Vamos a crear un csv aparte que contenga la información del hotel y otro csv con la información de los comentarios, para luego unirlos por el id del hotel.
#Para el csv de los hoteles, vamos a quedarnos con las columnas: web_scraper_start_url, nombre_del_hotel, y las que empiecen por "nota_". Para el csv de los comentarios, nos quedaremos con el resto de columnas, incluyendo el id del hotel que identificará cada hotel en el primer csv. 
#el id del hotel viene del nombre del hotel, que es único para cada hotel, así que lo usaremos como id para unir los csv después.

#creamos el csv de hoteles
columnas_hoteles = ['web_scraper_start_url', 'nombre_del_hotel'] + [col for col in df_total.columns if col.startswith('nota_')]
df_hoteles = df_total[columnas_hoteles].drop_duplicates()
df_hoteles.to_csv("df_hoteles_vlc_info.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_info.csv' creado con éxito!")

#creamos el csv de comentarios
columnas_comentarios = [col for col in df_total.columns if col not in columnas_hoteles]
df_comentarios = df_total[columnas_comentarios]
df_comentarios.to_csv("df_hoteles_vlc_comentarios.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_comentarios.csv' creado con éxito!")

¡Archivo 'df_hoteles_vlc_info.csv' creado con éxito!
¡Archivo 'df_hoteles_vlc_comentarios.csv' creado con éxito!

In [11]:
display(df_hoteles)

,web_scraper_start_url,nombre_del_hotel,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas
0,https://www.booking.com/hotel/es/melia-valenci...,Meliá Valencia,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6
3354,https://www.booking.com/hotel/es/the-river-hos...,The River Hostel,8.9,8.3,8.2,8.3,8.6,8.4,9.1,8.2
9888,https://www.booking.com/hotel/es/only-you-vale...,Only YOU Hotel Valencia,9.7,9.6,9.1,9.4,8.9,9.6,9.8,9.4
15225,https://www.booking.com/hotel/es/casual-valenc...,Casual del Cine Valencia by Casual Hoteles,9.4,8.7,8.8,8.3,8.4,8.8,9.7,8.5
19187,https://www.booking.com/hotel/es/nh-valencia-l...,NH Valencia Las Ciencias,8.7,8.2,7.8,7.8,7.6,8.4,8.9,7.9
23895,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2
33772,https://www.booking.com/hotel/es/renasa.es.htm...,Sweet Hotel Renasa,8.8,8.4,8.0,8.0,7.9,8.5,8.3,8.1
37763,https://www.booking.com/hotel/es/puertavalenci...,Silken Puerta Valencia,9.0,8.9,8.2,8.6,8.3,9.0,8.4,8.6
42175,https://www.booking.com/hotel/es/confortel-aqu...,Ilunion Aqua 3,8.6,8.2,8.5,7.8,7.6,8.3,9.0,7.9
46295,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8
48403,https://www.booking.com/hotel/es/las-arenas-ca...,Hotel Las Arenas Balneario Resort,8.9,8.9,8.3,8.6,8.5,8.9,9.2,8.6
51403,https://www.booking.com/hotel/es/casual-valenc...,Casual Vintage Valencia,9.3,8.6,8.6,8.2,8.4,8.7,9.8,8.4

## Limpieza (minúsculas, enlaces y caracteres, emoticonos)

In [12]:
import re
import demoji

# Traducir emojis
# Los traduce al inglés (tendremos que mirar si los traducimos al español todos o a qué idioma)
def handle_emoji(string):
    if not isinstance(string, str):
        return string
    emojis = demoji.findall(string)
    for emoji in emojis:
        string = string.replace(emoji, " [" + emojis[emoji].split(":")[0].strip() + "] ")
    return string

string_cols = df_comentarios.select_dtypes(include=['object', 'string']).columns
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.apply(handle_emoji))

# Todo a minúscula
string_cols = df_comentarios.select_dtypes(include=['object', 'string']).columns
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.lower())

# Eliminar enlaces y limpiar espacios
string_cols = df_comentarios.select_dtypes(include=['object', 'string']).columns
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.replace(r'https?://\S+|www\.\S+', '', regex=True).str.strip())

# Eliminar caracteres especiales
df_comentarios[string_cols] = df_comentarios[string_cols].apply(lambda col: col.str.replace(r'[^a-záéíóúüñàèìòùâêîôûäëïöüa-z0-9\s\[\].,!?;:\-]', ' ', regex=True))

In [13]:
df_comentarios.to_csv("df_comentarios_limpio.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_comentarios_limpio.csv' creado con éxito!")

¡Archivo 'df_comentarios_limpio.csv' creado con éxito!

In [14]:
display(df_comentarios)

,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,comentario_media_hotel
0,españa,habitación meliá con 1 cama extragrande,1,pareja,excelente,"todo la habitación súper amplia, la cama extra...",NaN,10.0,NaT,fabuloso
1,españa,habitación supreme,1,persona que viaja sola,mi referente para alojarme en valencia,ya lo conocía de anteriores estancias. me enca...,NaN,9.0,NaT,fabuloso
2,chile,habitación meliá con 1 cama extragrande,3,pareja,hotel funcional en lugar alejado,el lobby y cafeteria,ascensores lentos,8.0,NaT,fabuloso
3,españa,alojamiento the level supreme,3,familia,solo perfecto!,habitacion a la planta 24 high level - a est...,NaN,10.0,NaT,fabuloso
4,perú,habitación meliá,2,familia,fantástico,"habitación cómoda, la ubicación muy buena y el...",NaN,9.0,NaT,fabuloso
...,...,...,...,...,...,...,...,...,...,...
58715,países bajos,NaN,3,pareja,muy bien,NaN,NaN,8.0,NaT,muy bien
58716,italia,habitación interior individual pequeña,3,persona que viaja sola,fantástico,NaN,NaN,9.0,NaT,muy bien
58717,países bajos,habitación doble - 2 camas,2,pareja,muy bien,NaN,NaN,8.0,NaT,muy bien
58718,italia,habitación doble,2,pareja,excepcional,NaN,NaN,10.0,NaT,muy bien
58719,francia,NaN,1,pareja,agradable,NaN,NaN,6.0,NaT,muy bien