## UNIFICACIÓN DE DATOS DE WEB SCRAPING

In [29]:
import pandas as pd
import glob
import os

# 1. Le decimos a Python dónde están los archivos 
ruta = "*.csv" 

# 2. Buscamos todos los archivos CSV de la carpeta
archivos_csv = glob.glob(ruta)
print(f"He encontrado {len(archivos_csv)} archivos CSV para unir.")

# 3. Creamos una lista vacía y vamos leyendo y guardando cada CSV
lista_dataframes = []

for archivo in archivos_csv:
    # Leemos cada archivo (suponemos que están separados por comas)
    df_temporal = pd.read_csv(archivo)
    lista_dataframes.append(df_temporal)

# 4. Unimos todos los recortes en una sola tabla gigante
df_total = pd.concat(lista_dataframes, ignore_index=True)
print(f"Total de reseñas combinadas en bruto: {len(df_total)}")

# 5. Eliminar duplicados (mismo hotel o reseña 2 veces)
df_total = df_total.drop_duplicates()

# 6. Ética y Privacidad (Borramos el nombre del usuario si existe)
# Cambia 'nombre_usuario' por el nombre exacto que le pusisteis a esa columna en Web Scraper
nombre_columna_usuario = 'nombre_usuario' 
if nombre_columna_usuario in df_total.columns:
    df_total = df_total.drop(columns=[nombre_columna_usuario])
    print("✓ Nombres de usuario borrados por privacidad (Cumplimiento RGPD).")


print(f"Total de reseñas finales listas para NLP: {len(df_total)}")

# 7. Exportamos el súper archivo final
df_total.to_csv("df_hoteles_vlc_completo.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_completo.csv' creado con éxito!")

He encontrado 9 archivos CSV para unir.
Total de reseñas combinadas en bruto: 188568
✓ Nombres de usuario borrados por privacidad (Cumplimiento RGPD).
Total de reseñas finales listas para NLP: 125712
¡Archivo 'df_hoteles_vlc_completo.csv' creado con éxito!

In [30]:
display(df_total.head())

,web_scraper_order,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,...,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,1776264328-1,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,Colombia,NaN,2 noches ·,En familia,Espectacular,Espectacular todo! Restaurante; servicio; habi...,Todo me gustó,...,Fecha del comentario: 14 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
1,1776264328-2,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1 noche ·,En pareja,Muy bien,.,.,...,Fecha del comentario: 5 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
2,1776264328-3,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,2 habitaciones Dobles Deluxe comunicadas,1 noche ·,En familia,Fantástico,"Habitaciones amplias, limpieza y ubicación",NaN,...,Fecha del comentario: 3 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
3,1776264328-4,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1 noche ·,En pareja,Todo perfecto,El trato en recepción,El parking,...,Fecha del comentario: 21 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
4,1776264328-5,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,2 noches ·,En pareja,Una Nit del foc inolvidable.,Las vistas y el tamaño de la habitación.,"La calefacción central, sólo eso.",...,Fecha del comentario: 20 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso

In [31]:
#hacemos una copia del dataframe original para no perderlo
df_original= df_total.copy()

## Preprocesado y limpieza del dataset

In [32]:
#eliminar columna de web order
df_total = df_total.drop(columns=['web_scraper_order'])
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,Colombia,NaN,2 noches ·,En familia,Espectacular,Espectacular todo! Restaurante; servicio; habi...,Todo me gustó,10,Fecha del comentario: 14 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
1,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1 noche ·,En pareja,Muy bien,.,.,"9,0",Fecha del comentario: 5 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
2,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,2 habitaciones Dobles Deluxe comunicadas,1 noche ·,En familia,Fantástico,"Habitaciones amplias, limpieza y ubicación",NaN,"9,0",Fecha del comentario: 3 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
3,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1 noche ·,En pareja,Todo perfecto,El trato en recepción,El parking,10,Fecha del comentario: 21 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
4,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,2 noches ·,En pareja,Una Nit del foc inolvidable.,Las vistas y el tamaño de la habitación.,"La calefacción central, sólo eso.",10,Fecha del comentario: 20 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso

In [33]:
#de la columna noches extraemos el número de noches y actualizamos la columna, pasamos el digito a entero
df_total['noches'] = df_total['noches'].str.extract('(\d+)').astype(int)
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,Colombia,NaN,2,En familia,Espectacular,Espectacular todo! Restaurante; servicio; habi...,Todo me gustó,10,Fecha del comentario: 14 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
1,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Muy bien,.,.,"9,0",Fecha del comentario: 5 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
2,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,2 habitaciones Dobles Deluxe comunicadas,1,En familia,Fantástico,"Habitaciones amplias, limpieza y ubicación",NaN,"9,0",Fecha del comentario: 3 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
3,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Todo perfecto,El trato en recepción,El parking,10,Fecha del comentario: 21 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
4,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,2,En pareja,Una Nit del foc inolvidable.,Las vistas y el tamaño de la habitación.,"La calefacción central, sólo eso.",10,Fecha del comentario: 20 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso

In [34]:
#si la columna de negativo o positivo SOLO tiene un punto, lo convertimos a NA
df_total['negativo'] = df_total['negativo'].replace('.', pd.NA)
df_total['positivo'] = df_total['positivo'].replace('.', pd.NA)
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,Colombia,NaN,2,En familia,Espectacular,Espectacular todo! Restaurante; servicio; habi...,Todo me gustó,10,Fecha del comentario: 14 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
1,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Muy bien,<NA>,<NA>,"9,0",Fecha del comentario: 5 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
2,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,2 habitaciones Dobles Deluxe comunicadas,1,En familia,Fantástico,"Habitaciones amplias, limpieza y ubicación",NaN,"9,0",Fecha del comentario: 3 de abril de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
3,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Todo perfecto,El trato en recepción,El parking,10,Fecha del comentario: 21 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso
4,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,2,En pareja,Una Nit del foc inolvidable.,Las vistas y el tamaño de la habitación.,"La calefacción central, sólo eso.",10,Fecha del comentario: 20 de marzo de 2026,"9,1","9,2","8,5","8,8","8,4","9,2","9,2","8,8",Fabuloso

In [35]:
#todas las columnas de nota cambiamos las comas por puntos y las convertimos a numéricas
#coger las columnas que empiezan por 'nota'
columnas_notas = [col for col in df_total.columns if col.startswith('nota')]
for columna in columnas_notas:
    df_total[columna] = df_total[columna].str.replace(',', '.')
    df_total[columna] = pd.to_numeric(df_total[columna], errors='coerce')
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,Colombia,NaN,2,En familia,Espectacular,Espectacular todo! Restaurante; servicio; habi...,Todo me gustó,10.0,Fecha del comentario: 14 de abril de 2026,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
1,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Muy bien,<NA>,<NA>,9.0,Fecha del comentario: 5 de abril de 2026,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
2,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,2 habitaciones Dobles Deluxe comunicadas,1,En familia,Fantástico,"Habitaciones amplias, limpieza y ubicación",NaN,9.0,Fecha del comentario: 3 de abril de 2026,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
3,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Todo perfecto,El trato en recepción,El parking,10.0,Fecha del comentario: 21 de marzo de 2026,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
4,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,2,En pareja,Una Nit del foc inolvidable.,Las vistas y el tamaño de la habitación.,"La calefacción central, sólo eso.",10.0,Fecha del comentario: 20 de marzo de 2026,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso

In [36]:
#cogemos la columna de fecha, queremos quedarnos SOLO con la fecha y despues convertirla a formato datetime
#ahora las celdas son estilo: "Fecha del comentario, 14 de marzo de 2023"
df_total['fecha'] = df_total['fecha'].str.extract('(\d{1,2} de \w+ de \d{4})')
df_total['fecha'] = pd.to_datetime(df_total['fecha'], format='%d de %B de %Y', errors='coerce')
#quitar la hora de la fecha, solo queremos la fecha
df_total['fecha'] = df_total['fecha'].dt.date
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,Colombia,NaN,2,En familia,Espectacular,Espectacular todo! Restaurante; servicio; habi...,Todo me gustó,10.0,2026-04-14,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
1,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Muy bien,<NA>,<NA>,9.0,2026-04-05,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
2,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,2 habitaciones Dobles Deluxe comunicadas,1,En familia,Fantástico,"Habitaciones amplias, limpieza y ubicación",NaN,9.0,2026-04-03,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
3,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,En pareja,Todo perfecto,El trato en recepción,El parking,10.0,2026-03-21,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
4,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,2,En pareja,Una Nit del foc inolvidable.,Las vistas y el tamaño de la habitación.,"La calefacción central, sólo eso.",10.0,2026-03-20,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso

In [38]:
#quitar el "En" de la columna de personas, ahora tiene formato "En familia", "En pareja", "Solo", etc. Queremos quedarnos solo con el tipo de persona, sin el "En"
df_total['personas'] = df_total['personas'].str.replace('En ', '')
display(df_total.head())

,web_scraper_start_url,nombre_del_hotel,nacionalidad,detalles_hab,noches,personas,comentario_general,positivo,negativo,nota,fecha,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas,comentario_media_hotel
0,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,Colombia,NaN,2,familia,Espectacular,Espectacular todo! Restaurante; servicio; habi...,Todo me gustó,10.0,2026-04-14,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
1,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,pareja,Muy bien,<NA>,<NA>,9.0,2026-04-05,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
2,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,2 habitaciones Dobles Deluxe comunicadas,1,familia,Fantástico,"Habitaciones amplias, limpieza y ubicación",NaN,9.0,2026-04-03,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
3,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,1,pareja,Todo perfecto,El trato en recepción,El parking,10.0,2026-03-21,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso
4,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,España,NaN,2,pareja,Una Nit del foc inolvidable.,Las vistas y el tamaño de la habitación.,"La calefacción central, sólo eso.",10.0,2026-03-20,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8,Fabuloso

Vamos a crear un csv aparte que contenga la información del hotel y otro csv con la información de los comentarios, para luego unirlos por el id del hotel.
Para el csv de los hoteles, vamos a quedarnos con las columnas: web_scraper_start_url, nombre_del_hotel, y las que empiecen por "nota_". Para el csv de los comentarios, nos quedaremos con el resto de columnas, incluyendo el id del hotel que identificará cada hotel en el primer csv.

In [ ]:
#Vamos a crear un csv aparte que contenga la información del hotel y otro csv con la información de los comentarios, para luego unirlos por el id del hotel.
#Para el csv de los hoteles, vamos a quedarnos con las columnas: web_scraper_start_url, nombre_del_hotel, y las que empiecen por "nota_". Para el csv de los comentarios, nos quedaremos con el resto de columnas, incluyendo el id del hotel que identificará cada hotel en el primer csv. 
#el id del hotel viene del nombre del hotel, que es único para cada hotel, así que lo usaremos como id para unir los csv después.

#creamos el csv de hoteles
columnas_hoteles = ['web_scraper_start_url', 'nombre_del_hotel'] + [col for col in df_total.columns if col.startswith('nota_')]
df_hoteles = df_total[columnas_hoteles].drop_duplicates()
df_hoteles.to_csv("df_hoteles_vlc_info.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_info.csv' creado con éxito!")

#creamos el csv de comentarios
columnas_comentarios = [col for col in df_total.columns if col not in columnas_hoteles]
df_comentarios = df_total[columnas_comentarios]
df_comentarios.to_csv("df_hoteles_vlc_comentarios.csv", index=False, encoding='utf-8-sig')
print("¡Archivo 'df_hoteles_vlc_comentarios.csv' creado con éxito!")

¡Archivo 'df_hoteles_vlc_info.csv' creado con éxito!
¡Archivo 'df_hoteles_vlc_comentarios.csv' creado con éxito!

In [47]:
display(df_hoteles)

,web_scraper_start_url,nombre_del_hotel,nota_personal,nota_confort,nota_wifi,nota_instalaciones_servicios,nota_calidad_precio,nota_limpieza,nota_ubicacion,nota_media_resenas
0,https://www.booking.com/hotel/es/barcelo-valen...,Barceló Valencia,9.1,9.2,8.5,8.8,8.4,9.2,9.2,8.8
6324,https://www.booking.com/hotel/es/venecia.es.ht...,Venecia Plaza Centro,9.5,9.4,8.9,9.1,9.0,9.4,9.9,9.2
16201,https://www.booking.com/hotel/es/las-arenas-ca...,NaN,8.9,8.9,8.3,8.6,8.5,8.9,9.2,8.6
19201,https://www.booking.com/hotel/es/casual-valenc...,NaN,9.3,8.6,8.6,8.2,8.4,8.7,9.8,8.4
26518,https://www.booking.com/hotel/es/only-you-vale...,Only YOU Hotel Valencia,9.7,9.6,9.1,9.4,8.9,9.6,9.8,9.4
31855,https://www.booking.com/hotel/es/casual-valenc...,Casual del Cine Valencia by Casual Hoteles,9.4,8.7,8.8,8.3,8.4,8.8,9.7,8.5
35817,https://www.booking.com/hotel/es/melia-valenci...,NaN,9.0,9.1,NaN,8.8,8.3,9.0,8.3,8.6
39171,https://www.booking.com/hotel/es/the-river-hos...,NaN,8.9,8.3,8.2,8.3,8.6,8.4,9.1,8.2
45705,https://www.booking.com/hotel/es/renasa.es.htm...,Sweet Hotel Renasa,8.8,8.4,8.0,8.0,7.9,8.5,8.3,8.1
49696,https://www.booking.com/hotel/es/puertavalenci...,Silken Puerta Valencia,9.0,8.9,8.2,8.6,8.3,9.0,8.4,8.6
54108,https://www.booking.com/hotel/es/confortel-aqu...,Ilunion Aqua 3,8.6,8.2,8.5,7.8,7.6,8.3,9.0,7.9
58240,https://www.booking.com/hotel/es/confortel-aqu...,Ilunion Aqua 3,8.6,8.2,8.5,7.8,7.6,8.3,9.0,7.9
62364,https://www.booking.com/hotel/es/nh-valencia-l...,NH Valencia Las Ciencias,8.7,8.2,7.8,7.8,7.6,8.4,8.9,7.9